### ISSUE TITLE
Missing tag on GitHub

### ISSUE THREAD

**Issue by franzlst** [Kavantix/sliver_tools#87]
We are using [ort](https://github.com/oss-review-toolkit/ort/) for automatic software compliance checks.

sliver_tools is one of our dependencies and we use it in version 0.2.12. Now, ort fails in scanning this repo, as this version is not tagged on GitHub.

Could you please add the missing tag "0.2.12" to GitHub and keep these tags in sync with upcoming releases?

**Comment by Kavantix** [comment]
@franzlst I've added the tag.

But I would recommend looking into not depending on the GitHub tags. Pub packages are always open source so you should not need the GitHub tag.
And on top of that relying on the GitHub tag isn't a good idea since it might be completely different than the version on pub.

If you do want to rely on GitHub instead of pub you could also use git dependencies: https://dart.dev/tools/pub/dependencies#git-packages

**Comment by franzlst** [comment]
@Kavantix Thanks a lot. I fully agree with you. Unfortunately, I do not have direct access to the tool sources I use, but there is already an open ticket requesting a change in that direction.
